"use strict";

export const items = [
    { name: "Shampoo", category: "Hygiene", price: 5.99, brand: "Head & Shoulders", stock: 59 },
    { name: "Toothpaste", category: "Hygiene", price: 2.99, brand: "Colgate", stock: 120 },
    { name: "Body Wash", category: "Hygiene", price: 4.99, brand: "Dove", stock: 85 },
    { name: "Hand Sanitizer", category: "Hygiene", price: 3.49, brand: "Purell", stock: 150 },
    { name: "Deodorant", category: "Hygiene", price: 5.49, brand: "Old Spice", stock: 60 },
    { name: "Face Cream", category: "Hygiene", price: 12.99, brand: "Nivea", stock: 45 },
    { name: "Toilet Paper", category: "Household", price: 8.99, brand: "Charmin", stock: 200 },
    { name: "Paper Towels", category: "Household", price: 5.49, brand: "Bounty", stock: 110 },
    { name: "Dish Soap", category: "Household", price: 2.99, brand: "Dawn", stock: 130 },
    { name: "Laundry Detergent", category: "Household", price: 10.99, brand: "Tide", stock: 75 },
    { name: "All-Purpose Cleaner", category: "Household", price: 3.99, brand: "Lysol", stock: 95 },
    { name: "Garbage Bags", category: "Household", price: 6.49, brand: "Glad", stock: 85 },
    { name: "Batteries", category: "Electronics", price: 7.99, brand: "Duracell", stock: 50 },
    { name: "Phone Charger", category: "Electronics", price: 14.99, brand: "Anker", stock: 40},
    { name: "Bluetooth Speaker", category: "Electronics", price: 29.99, brand: "JBL", stock: 30},
    { name: "Headphones", category: "Electronics", price: 19.99, brand: "Sony", stock: 35 },
    { name: "Smart Watch", category: "Electronics", price: 199.99, brand: "Apple", stock: 20 },
    { name: "Laptop", category: "Electronics", price: 799.99, brand: "Dell", stock: 10 },
    { name: "Mouse", category: "Electronics", price: 12.99, brand: "Logitech", stock: 60 },
    { name: "Keyboard", category: "Electronics", price: 24.99, brand: "Microsoft", stock: 45 },
    { name: "Cereal", category: "Grocery", price: 3.99, brand: "Kellogg's", stock: 100 },
    { name: "Pasta", category: "Grocery", price: 1.49, brand: "Barilla", stock: 150 },
    { name: "Tomato Sauce", category: "Grocery", price: 2.49, brand: "Ragu", stock: 120 },
    { name: "Olive Oil", category: "Grocery", price: 7.99, brand: "Bertolli", stock: 80 },
    { name: "Peanut Butter", category: "Grocery", price: 3.49, brand: "Jif", stock: 90 },
    { name: "Jam", category: "Grocery", price: 2.99, brand: "Smucker's", stock: 95 },
    { name: "Coffee", category: "Grocery", price: 9.99, brand: "Folgers", stock: 70 },
    { name: "Tea", category: "Grocery", price: 4.99, brand: "Lipton", stock: 85 },
    { name: "Soda", category: "Grocery", price: 1.99, brand: "Coca-Cola", stock: 200 },
    { name: "Water", category: "Grocery", price: 0.99, brand: "Evian", stock: 300 },
    { name: "Juice", category: "Grocery", price: 2.49, brand: "Tropicana", stock: 100 },
    { name: "Milk", category: "Grocery", price: 2.99, brand: "Horizon", stock: 110 },
    { name: "Eggs", category: "Grocery", price: 1.99, brand: "Eggland's Best", stock: 130 },
    { name: "Bread", category: "Grocery", price: 2.49, brand: "Wonder", stock: 140 },
    { name: "Butter", category: "Grocery", price: 3.49, brand: "Land O'Lakes", stock: 90 },
    { name: "Cheese", category: "Grocery", price: 4.99, brand: "Kraft", stock: 85 },
    { name: "Yogurt", category: "Grocery", price: 1.49, brand: "Chobani", stock: 120 },
    { name: "Chicken Breast", category: "Grocery", price: 6.99, brand: "Tyson", stock: 60 },
    { name: "Ground Beef", category: "Grocery", price: 5.99, brand: "Oscar Mayer", stock: 70 },
    { name: "Salmon Fillet", category: "Grocery", price: 8.99, brand: "Sea Best", stock: 50 },
    { name: "Broccoli", category: "Grocery", price: 1.99, brand: "Green Giant", stock: 100 },
    { name: "Carrots", category: "Grocery", price: 1.49, brand: "Bolthouse Farms", stock: 120 },
    { name: "Apples", category: "Grocery", price: 2.99, brand: "Granny Smith", stock: 130 },
    { name: "Bananas", category: "Grocery", price: 1.29, brand: "Dole", stock: 150 },
    { name: "Grapes", category: "Grocery", price: 2.99, brand: "Del Monte", stock: 140 },
    { name: "Oranges", category: "Grocery", price: 3.99, brand: "Sunkist", stock: 110 },
    { name: "Chips", category: "Grocery", price: 2.99, brand: "Lay's", stock: 150 },
    { name: "Cookies", category: "Grocery", price: 3.49, brand: "Oreo", stock: 140 }
];